<div class="field field-linkedin_profile">
    <label class="label" for="linkedin_profile">
        <span><?= __('LinkedIn Profile') ?></span>
    </label>
    <div class="control">
        <input
            type="text"
            id="linkedin_profile"
            name="linkedin_profile"
            class="input-text"
            data-validate='{"required":true, "validate-url":true}'
            maxlength="250"
        />
    </div>
</div>
